application: gae-scaffold
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

handlers:
#- url: /remote_api
#  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
#  login: admin

- url: /css
  static_dir: htdocs/css

- url: /js
  static_dir: htdocs/js

- url: /.*
  script: main.app
#  login: required

#inbound_services:
#- warmup

#builtins:
#- remote_api: on
